spring:
  application:
    name: home-made-instagram
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DB_NAME:insta_home}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      
## Multipart config
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      
#custom properties
jsonwebtoken:
  secretKey: ${JWT_SECRET:E238B9257E8AEF5543458721BE85A}
  issuer: ${JWT_ISSUER:com.instagram}
  
 ## File upload custom properties
file:
  upload:
    location: /d/insta-assets/images
  
